openapi: "3.0.3"
info:
  title: Event API
  version: "1.0"
servers:
  - url: http://localhost:8080
paths:
  /events:
    get:
      tags:
        - events
      operationId: findEvents
      description: |
        Return Events Data.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Event"
    post:
      tags:
        - events
      operationId: createEvent
      description: |
        Create New Events Data.
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Id"
  /events/{eventId}:
    get:
      tags:
        - events
      operationId: findEvent
      description: |
        Return Event Data.
      parameters:
        - name: eventId
          in: path
          description: Event ID
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Event"
    put:
      tags:
        - events
      operationId: updateEvent
      description: |
        Update Event Data.
      parameters:
        - name: eventId
          in: path
          description: Event ID
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "204":
          description: Updated
    delete:
      tags:
        - events
      operationId: deleteEvent
      description: |
        Delete Event Data.
      parameters:
        - name: eventId
          in: path
          description: Event ID
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "204":
          description: Deleted

components:
  schemas:
    Event:
      allOf:
        - $ref: "#/components/schemas/NewEvent"
        - $ref: "#/components/schemas/Id"

    Id:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          format: uuid

    NewEvent:
      type: object
      required:
        - name
        - description
        - startAt
      properties:
        name:
          type: string
        description:
          type: string
        startAt:
          type: string
          format: date-time
        endAt:
          type: string
          format: date-time
